### ISSUE TITLE
Invalid Maximun Heap Error...?

### ISSUE THREAD

**Issue by theotherdragon** [ynvaser/deckscraper#1]
Hello, I'm attempting to use the deckscrapper as described however I'm running into an issue.

"Invalid maximum heap size: -Xmx4G
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit."

I have Java 14 SE installed. Have any idea how to fix this?

Edit: I needed Java 64 Bit installed turns out.

**Comment by ynvaser** [comment]
The tool requires Java 17 or newer to run.
