### ISSUE TITLE
No EDHrec lists in latest Release

### ISSUE THREAD

**Issue by Kil-Rec** [ynvaser/deckscraper#4]
Hello ynvaser,

first of all: Really great tool and thank you for taking the time and dedication to build it!

~~Using the start.bat in the latest release the output folder only contains a "_cube" subfolder and no decks from EDHrec.~~
The error was, that in the "applications.propertier" the monthsToLookBack was only set to 1 and there where no decks in that time for which I had more than "normalDeckThreshold" percent of cards. 

However, I think a good feature would be to write out a "no_decks_found.txt" which tells the user to change the properties.

**Comment by ynvaser** [comment]
Thanks for the suggestion, I'll add it to my backlog.
