### ISSUE TITLE
Bypassing moxfield's scraping detector, a solution

### ISSUE THREAD

**Issue by thebear132** [ynvaser/deckscraper#8]
I have a similiar program which also downloads decks from Moxfield, here is how to bypass it if you are interested! Any questions, feel free to message me
https://github.com/thebear132/MTG-To-XMage/commit/0272d5914efcdc7c5f1ceaed27b21409c7ac02a8

**Comment by thebear132** [comment]
Check the changes in *program.py*, just change your user agent when sending the request from (in my case) "python-requests..." to some random valid user agent

**Comment by ynvaser** [comment]
Thanks for the suggestion, @thebear132, i'll take a look once I can pick this up again.
